#spring.application.name=payments-service

spring:
  r2dbc:
    name:
    url: r2dbc:mysql://localhost:3306/test
    username: root
    password: 1234

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
